# Generated by Django 5.2 on 2025-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_gameboard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameboard",
            old_name="created_ad",
            new_name="created_at",
        ),
    ]
